development:
  clients:
    default:
      database: looking2_dev
      hosts:
        - localhost:27017
      options:
  options:
# test:
#   clients:
#     default:
#       database: looking2_test
#       hosts:
#         - localhost:27017
#       options:
#         read:
#           mode: :primary
#         max_pool_size: 1
production:
    clients:
        default:
            database: looking2
            hosts:
                - localhost:27017
            options: