# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba8a9acdb7e4deef4914e1be68a57a978b2455f341f8233800af038a668cde1c069112608d526dc857f0a3a9c3125de26b1cb893cf3ace77afde48c0dde4fdd1

test:
  secret_key_base: 58659071dd2dafd3c9a16f51ef3084dfc5bec32c63582d8baacb0f8519b3a5d45d8bbdfc4902c37cfa7ac7eac06dcae0d30063d4ccdaac52a42d81d55234a051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
